# Generated by Django 3.1.2 on 2020-10-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_ok',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='running_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
