# Generated by Django 3.1.2 on 2020-10-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TfeiTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tw_screen_name', models.CharField(max_length=30)),
                ('tw_id', models.BigIntegerField()),
                ('task_type', models.CharField(max_length=6)),
                ('task_status', models.CharField(max_length=20)),
                ('pending_at', models.DateTimeField(auto_now_add=True)),
                ('running_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('finished_ok', models.BooleanField(null=True)),
                ('finished_details', models.TextField(blank=True)),
            ],
        ),
    ]
