# Generated by Django 3.1.2 on 2020-11-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwUser',
            fields=[
                ('tw_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tw_screen_name', models.CharField(max_length=30)),
                ('tw_token', models.CharField(max_length=100)),
                ('tw_token_sec', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_screen_name_for_task', models.CharField(max_length=30)),
                ('task_type', models.CharField(max_length=20)),
                ('task_status', models.CharField(max_length=20)),
                ('task_par_tw_id', models.BigIntegerField()),
                ('task_par_f_name', models.CharField(max_length=100)),
                ('pending_at', models.DateTimeField(auto_now_add=True)),
                ('running_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('finished_ok', models.BooleanField(null=True)),
                ('finished_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tw_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tfei.twuser')),
            ],
        ),
    ]
