# Generated by Django 3.1.2 on 2020-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfei', '0003_auto_20201110_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_output',
            field=models.TextField(blank=True),
        ),
    ]
