# Generated by Django 3.1.2 on 2020-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfei', '0004_task_finished_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
