# Generated by Django 3.1.2 on 2020-12-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfei', '0005_auto_20201203_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_par_tw_id',
        ),
        migrations.AddField(
            model_name='task',
            name='par_exp_screen_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
