# Generated by Django 3.1.2 on 2020-12-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfei', '0006_auto_20201207_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_par_f_name',
        ),
        migrations.AddField(
            model_name='task',
            name='par_imp_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
